//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdExpediente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Horario { get; set; }
        public string Modalidad { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Expediente Expediente { get; set; }
    }
}
